<?php

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
?>
<div class="wrap">
	<h1><?php esc_html_e( 'Reader Settings', 'feed-reader' ); ?></h1>

	<form action="options.php" method="post">
		<?php
		settings_fields( 'feed-reader-settings-group' );
		$options = get_option( 'feed_reader_settings' );
		?>

		<table class="form-table">
			<tr valign="top">
				<th scope="row"><?php esc_html_e( 'Show Actions', 'feed-reader' ); ?></th>
				<td>
					<label><input type="checkbox" name="feed_reader_settings[show_actions]" <?php checked( ! empty( $options['show_actions'] ) ); ?> /> <?php esc_html_e( 'Display &ldquo;action buttons&rdquo; below single entries', 'feed-reader' ); ?></label>
					<p class="description"><?php esc_html_e( 'These allow you to reply to, favorite, or bookmark feed entries, directly from the reader.', 'feed-reader' ); ?></p>
				</td>
			</tr>
			<tr valign="top">
				<th scope="row"><?php esc_html_e( 'Image Proxy', 'feed-reader' ); ?></th>
				<td>
					<label><input type="checkbox" name="feed_reader_settings[image_proxy]" <?php checked( ! empty( $options['image_proxy'] ) ); ?> /> <?php esc_html_e( '(Experimental) &ldquo;Proxy&rdquo; images and video', 'feed-reader' ); ?></label>
					<p class="description"><?php esc_html_e( 'Avoid &ldquo;mixed context&rdquo; errors when reading feeds.', 'feed-reader' ); ?></p>

					<div style="margin-block-start: 0.5em; margin-inline-start: 1.5em;">
						<label><input type="checkbox" name="feed_reader_settings[image_proxy_http_only]" <?php checked( ! empty( $options['image_proxy_http_only'] ) ); ?> /> <?php esc_html_e( '&ldquo;Proxy&rdquo; HTTP URLs only', 'feed-reader' ); ?></label>
						<p class="description"><?php esc_html_e( 'Save (some) bandwith by &ldquo;rewriting&rdquo; only non-HTTPS URLs.', 'feed-reader' ); ?></p>
					</div>
				</td>
			</tr>
			<tr valign="top">
				<th scope="row"><label for="feed-reader-image-proxy-secret"><?php esc_html_e( 'Image Proxy Secret', 'feed-reader' ); ?></label></th>
				<td>
					<input type="text" name="feed_reader_settings[image_proxy_secret]" id="feed-reader-image-proxy-secret" style="min-width: 25%;" value="<?php echo ! empty( $options['image_proxy_secret'] ) ? esc_attr( $options['image_proxy_secret'] ) : ''; ?>" />
					<button type="button" class="button" id="feed-reader-generate-secret"><?php esc_html_e( 'Generate', 'feed-reader' ); ?></button>
					<p class="description"><?php esc_html_e( 'To work, the image proxy needs a (sufficiently random) secret, much like an autogenerated password.', 'feed-reader' ); ?></p>
				</td>
			</tr>
		</table>

		<p class="submit">
			<button type="submit" class="button button-primary"><?php esc_html_e( 'Save Changes', 'feed-reader' ); ?></button>
		</p>
	</form>
</div>
